x = x.g[5].h > 10
-- function print(a, b, c)
--     some(a, b, c)
--     do
--         some(a, b, c)
--         return some
--         some(a, b, c)
--         return some2 + some
--     end
-- end
-- repeat
--     if x.g[5].h > 10 then
--         print(1, 2, 2 / 5)
--     else
--         print(5)
--     end
-- until x > 10
-- print(15)